DROP TABLE IF EXISTS webhook_deliveries;
DROP TABLE IF EXISTS webhook_endpoints;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS email_events;
DROP TABLE IF EXISTS emails;
DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS users;